appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: FyZpAEEIe5/jHQ7uYxOkG+UpOIKFoLwz7ylFzNw+LJz5V5//YAh1v6KlZ/A/BxZXoVRE09qLl8VaQ2hmuGKv9Ywk0VO/qHTf0FvmfzINx297XVLHUYgVE+/DKBD92qzF3ZGg7RzTRJ7u7uT4EN0osrdTFCQJciDWdRCc02CwagVL4k7FRiU9zUwCl9TFKOX4X3xtXYuiIIq5tuJgRjkQaDQx06gQhHVbYQoeD+G3OYb1Nisb2Hv+IzU6UjHobCL7IyFc5ki+VA7taEOkB3Q1EwfKAyFHxSH+DqUrd/l14ojfiJpx4VH20p1q7pl40jDoiV3VqM1H3if9TFeOsNaYpd3kCN5ksO9kIBDZUvxfFJpHghX6VU8OXYn86jRzCT9mp4JrQ19/MT7re299xJIjARZunoaKTv3bmMWxUMFFcK7n7tFqB8BXcswAX8m4iMXqNyKC25+Nifdp7LNBOa0TTx0g/Ujp4gxpc2MYrD3gDWasj++VKwGfXNNUhzvKMZRvtoR6NxWKVOZOggqEE9Ojzb4AwfEy1icl2qxCPPQveuy/KLRebpBJFRPkWj/Yn/z6rXvgwqfOYX99obqdseU3guSglXz7MrxwRYUdWEy2h/6vv7S6L9a3y0WleCIeBQ2sWgyu0uKjP7fw0J3A/AjKBIJznrr0JHSexu5SMXJcpdA=}
